import { IExpedition } from "../types/expedition";

export const _ekspedisi: IExpedition[] = [
    {
        "id": "jne",
        "name": "JNE",
        "code": "JNE",
        "icon": "https://images.seeklogo.com/logo-png/13/1/tiki-jne-logo-png_seeklogo-139992.png",
        "private": false,
    },
    {
        "id": "jne2alt",
        "name": "JNE",
        "code": "JNE2ALT",
        "icon": "https://images.seeklogo.com/logo-png/13/1/tiki-jne-logo-png_seeklogo-139992.png",
        "private": false,
    },
    {
        "id": "jet",
        "name": "J&T Express",
        "code": "JET",
        "icon": "https://images.seeklogo.com/logo-png/33/1/jt-express-logo-png_seeklogo-336498.png",
        "private": false,
    },
    {
        "id": "jtcargo",
        "name": "J&T Cargo",
        "code": "JTCARGO",
        "icon": "https://images.seeklogo.com/logo-png/44/1/jt-cargo-logo-png_seeklogo-447496.png",
        "private": false,
    },
    {
        "id": "sicepat",
        "name": "SiCepat",
        "code": "SICEPAT",
        "icon": "https://images.seeklogo.com/logo-png/33/1/sicepat-ekspres-logo-png_seeklogo-339931.png",
        "private": false,
    },
    {
        "id": "lion",
        "name": "Lion Parcel",
        "code": "LIONPARCEL",
        "icon": "",
        "private": false,
    },
    {
        "id": "anteraja",
        "name": "Anteraja",
        "code": "ANTERAJA",
        "icon": "https://www.epeken.com/main/wp-content/uploads/2021/05/icon-256x256-1.png",
        "private": false,
    },
    {
        "id": "tiki",
        "name": "Tiki",
        "code": "TIKI",
        "icon": "https://images.seeklogo.com/logo-png/13/1/tiki-logo-png_seeklogo-139990.png",
        "private": false,
    },
    {
        "id": "jdl",
        "name": "JDL Express",
        "code": "JDL",
        "icon": "https://prod-talentics-storage.s3.ap-southeast-1.amazonaws.com/organizations/109204/logos/1652838459_9a556a211db4f4d5399b98f2c59bfcbfc6c041cc.png",
        "private": false,
    },
    {
        "id": "jx",
        "name": "JX/J-Express",
        "code": "JX",
        "icon": "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEgNJM8tWn2c_TGq71g4clojksw57rDn_XH06finl6NgQV-6U6cNgEVDyM4Z5QUpHv1x9Hq-BlwRbDohXA10l5d1nHorcA2R3MoGSxcd_6v8LL-cDEnZCjFXOuBTV3SQ6xOD8759p72bY_kDME5vQikar859isFa5noQAgPZ84OkVkGmbOxz_W7M3W8E/s320/GKL37_JX%20Express%20-%20Koleksilogo.com.jpg",
        "private": false,
    },
    {
        "id": "pahala",
        "name": "Pahala Express",
        "code": "PAHALA",
        "icon": "https://storage.googleapis.com/komerce/rajaongkir/pahala-express.png",
        "private": false,
    },
    {
        "id": "indah",
        "name": "Indah Logistik Cargo",
        "code": "INDAH",
        "icon": "https://iconlogovector.com/uploads/images/2023/11/lg-655da2184389c-indah-cargo-logistik.png",
        "private": false,
    },
    {
        "id": "oexpress",
        "name": "OExpress",
        "code": "oexpress",
        "icon": "https://oexpress.id/wp-content/uploads/2023/09/oex.jpg",
        "private": false,
    },
    {
        "id": "rpx",
        "name": "RPX Holding",
        "code": "RPX",
        "icon": "https://images.seeklogo.com/logo-png/33/2/rpx-logistics-logo-png_seeklogo-339965.png",
        "private": false,
    },
    {
        "id": "rex",
        "name": "REX Indonesia",
        "code": "REX",
        "icon": "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEgVSeKIX7EVumOumIlM4WYBDuf0XLWmLW8_WJAgwvBNzzDxzWGhSMJjTU8f_OQCEnz9c5tiMQa8_fcoBCdcbQ353QhOrfq32uIum1w2xDvDqvHAfX4YLqUOdXt-ek1xPnJvUY65iDbTyMmz6dep443q77PvMemAcD9ZC2pO3UcAhZpG9Y68UyMSaiRM/s320/GKL44_REX%20Indonesia%20-%20Koleksilogo.com.jpg",
        "private": false,
    },
    {
        "id": "21",
        "name": "21 Express",
        "code": "DUASATU",
        "icon": "https://storage.googleapis.com/10fd8335-c083-4a36-96db-aba9f5867c51/web-assets/cpr/9BPaWl7U7axu6m3p/9db979f1-4b9d-406a-a2a5-c659745b33fa",
        "private": false,
    },
    {
        "id": "ikea",
        "name": "IKEA",
        "code": "IKEA",
        "icon": "",
        "private": false,
    },
    {
        "id": "skynet",
        "name": "SKYNET",
        "code": "SKYNET",
        "icon": "",
        "private": false,
    },
    {
        "id": "asp",
        "name": "ASP Express",
        "code": "ASP",
        "icon": "",
        "private": false,
    },
    {
        "id": "rosalia",
        "name": "Rosalia Express",
        "code": "ROSALIA",
        "icon": "",
        "private": false,
    },
    {
        "id": "fedex",
        "name": "FedEx",
        "code": "fedex",
        "icon": "",
        "private": true,
    },
    {
        "id": "herona",
        "name": "Herona Express",
        "code": "HERONA",
        "icon": "",
        "private": false,
    },
    {
        "id": "sajira",
        "name": "SAJIRA",
        "code": "sajira",
        "icon": "",
        "private": true,
    },
    {
        "id": "bea-cukai",
        "name": "Luar Negeri / Bea Cukai",
        "code": "BEACUKAI",
        "icon": "",
        "private": false,
    },
    {
        "id": "wahana",
        "name": "WAHANA",
        "code": "WAHANA",
        "icon": "",
        "private": false,
    },
    {
        "id": "wahana2alt",
        "name": "WAHANA",
        "code": "WAHANA2ALT",
        "icon": "",
        "private": false,
    },
    {
        "id": "sentralcargo",
        "name": "Sentral Cargo",
        "code": "SENTRALCARGO",
        "icon": "",
        "private": false,
    },
    {
        "id": "gojek",
        "name": "Gojek / GoSend",
        "code": "gojek",
        "icon": "",
        "private": true,
    },
    {
        "id": "first",
        "name": "First Logistics",
        "code": "FIRST",
        "icon": "",
        "private": false,
    },
    {
        "id": "citox",
        "name": "CitoXpress",
        "code": "CITOX",
        "icon": "",
        "private": false,
    },
    {
        "id": "ark",
        "name": "ARK Xpress",
        "code": "ARK",
        "icon": "",
        "private": false,
    },
    {
        "id": "laris",
        "name": "Laris Cargo",
        "code": "laris",
        "icon": "",
        "private": true,
    },
    {
        "id": "spx",
        "name": "Shopee Express (SPX)",
        "code": "SPX",
        "icon": "",
        "private": false,
    },
    {
        "id": "ninja",
        "name": "Ninja",
        "code": "NINJA",
        "icon": "",
        "private": false,
    },
    {
        "id": "pos",
        "name": "POS Indonesia",
        "code": "POS",
        "icon": "",
        "private": false,
    },
    {
        "id": "acommerce",
        "name": "Acommerce",
        "code": "acommerce",
        "icon": "",
        "private": false,
    },
    {
        "id": "gtl",
        "name": "GTL Goto Logistics",
        "code": "GTL",
        "icon": "",
        "private": false,
    },
    {
        "id": "paxel",
        "name": "Paxel",
        "code": "paxel",
        "icon": "",
        "private": false,
    },
    {
        "id": "sap",
        "name": "SAP Express",
        "code": "SAP",
        "icon": "",
        "private": false,
    },
    {
        "id": "lex",
        "name": "Lazada Express (LEX)",
        "code": "lex",
        "icon": "",
        "private": false,
    },
    {
        "id": "lel",
        "name": "Lazada Logistics",
        "code": "lel",
        "icon": "",
        "private": false,
    },
    {
        "id": "janio",
        "name": "Janio Asia",
        "code": "janio",
        "icon": "",
        "private": false,
    },
    {
        "id": "jet-express",
        "name": "Jet Express",
        "code": "jetexpress",
        "icon": "",
        "private": false,
    },
    {
        "id": "pcp",
        "name": "PCP Express",
        "code": "PCP",
        "icon": "",
        "private": false,
    },
    {
        "id": "ncs",
        "name": "PT NCS",
        "code": "NCS",
        "icon": "",
        "private": false,
    },
    {
        "id": "nss",
        "name": "NSS Express",
        "code": "NSS",
        "icon": "",
        "private": false,
    },
    {
        "id": "rcl",
        "name": "RCL Red Carpet Logistics",
        "code": "RCL",
        "icon": "",
        "private": false,
    },
    {
        "id": "grab",
        "name": "Grab Express",
        "code": "grab",
        "icon": "",
        "private": true,
    },
    {
        "id": "qrim",
        "name": "Qrim Express",
        "code": "QRIM",
        "icon": "",
        "private": false,
    },
];